proc jc_wrapBS(){
    global string $newSource;
    global string $oldSource;
    global string $oldTargets[];
	window -title "jc_wrapBS" -w 300 -h 200;
    // columnLayout;
    // columnLayout -adjustableColumn true;
    columnLayout -columnAttach "both" 5 -rowSpacing 5 -columnWidth 100;
    button -label "New Source" -command "jc_wrapBS_addNewSource()";
    button -label "Old Source" -command "jc_wrapBS_addOldSource()";
    button -label "Old Targets" -command "jc_wrapBS_addOldDest()";
    button -label "Run!" -command "jc_wrapBS_run";
	showWindow;
}

proc jc_wrapBS_addNewSource(){
    string $selection[] = `ls -sl`;
    global string $newSource;
    $newSource = $selection[0];
    print ("addNewSource = " + $newSource+ "\n");
    
}

proc jc_wrapBS_addOldSource(){
    string $selection[] = `ls -sl`;
    global string $oldSource;
    $oldSource = $selection[0];
    print ("addOldSource = " + $oldSource+ "\n");
}

proc jc_wrapBS_addOldDest(){
    global string $oldTargets[];
    $oldTargets = `ls -sl`;
    for ($i in $oldTargets) {
    print ("addOldDest = " + $i + "\n");
    }
}

proc jc_wrapBS_run(){
    global string $newSource;
    global string $oldSource;
    global string $oldTargets[];
    string $sel;
    print "Running wrapBS!\n";
    print ("NewSource = " + $newSource+ "\n");
    print ("OldSource = " + $oldSource+ "\n");
    print ("OldDest = " + $oldTargets[0] + "\n");
    string $newGroup = `group -em -name wrapGroup`;
    
    // create deformer, need to learn what do Wrap args do!
    select -r $newSource $oldSource; 
    string $wrapName[] = `doWrapArgList "2" { "1","0","1" }`;
    print ("name of wrap deformer node: " + $wrapName[0]); 

    // create blendshape
    select -r $oldTargets $oldSource;
    string $blendContainer[] = `blendShape`;
    
    // iterate blend to all the targets
   for ($sel in $oldTargets){
       setAttr ($blendContainer[0] + "." + $sel) 1;
       $dupVar = `duplicate $newSource`;
       $renamed = `rename $dupVar $sel`;
       parent $renamed $newGroup;
       setAttr ($blendContainer[0] + "." + $sel) 0;
   }
   print "RUN HAS ENDED\n";
   print $wrapName[0];
   print $blendContainer[0];
   //delete extranese nodes
   delete $blendContainer[0] $wrapName[0]; 
}

jc_wrapBS();
