#!/usr/bin/env python2.7

"""
will combine while retaining the pivot, name, hierarchy, and display layer of the last
selected object. history is deleted

__author__: James Chan
"""

import maya.cmds as cmds

def smartCombine():
    selection = cmds.ls(sl=True, o=True)
    main = selection[-1] # main is reference for pivot, name, display layers, hierarchy
    parents = cmds.listRelatives(main, parent=True, fullPath=True)
    display_layers = cmds.listConnections(main, type="displayLayer")
    pivotInfo = cmds.xform(main, q=True, pivots=True, ws=True)[:3]
    print "main:", main
    print parents
    #run combine, add to original heirarchy
    newMesh = cmds.polyUnite(selection, ch=True)[0]

    print newMesh
    if parents:
        newName = cmds.parent(newMesh, parents[0])
        newMesh = newName

    # delete history, add to original display layer, set pivot, add original name
    cmds.delete(newMesh, ch=True)
    if display_layers:
        cmds.editDisplayLayerMembers(display_layers[0], newMesh)
    cmds.xform(newMesh, pivots=pivotInfo, ws=True)
    cmds.rename(newMesh, main.split("|")[-1])

    return
